---
- name: Create {{ cloud }} Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Including {{ cloud }} role for infrastructure creation
      include_role:
        name: role-ec2
      vars:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
      when: cloud == "AWS"

    - name: Including {{ cloud }} role for infrastructure creation
      include_role:
        name: role-ec2
      when: cloud == "Azure"
      
