---
- debug:
    msg: '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}' 
- name: Create a security group
  ec2_group:
    aws_access_key: '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
    aws_secret_key: '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'
    name: "{{ ec2_sg }}"
    description: Security group
    region: "{{ ec2_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
